### ISSUE TITLE
Spec: max message length

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-condition#20]
Similar to how there is a `maxFulfillmentLength`, I think there should be a `maxMessageLength`. This is unusual for a signature scheme but we want to prevent the case where someone can set up conditions on multiple systems knowing that a message + fulfillment will be valid on one but not the other.

**Comment by justmoon** [comment]
Perhaps the best way to think about crypto-conditions are as a signature scheme. Most signature schemes have a fixed signature size, however, since crypto-conditions allow arbitrarily sized groups of signers, we have variable sized signatures.

The application that is using crypto-conditions has no insight into how large of a signature it should expect, which is why we need a facility (`maxFulfillmentLength`) to limit that size.

The message can also be arbitrarily large, so do we need the same for the message as well? I would argue, no, because the message *is* part of the application domain and the application *does* have visibility into how large of a message it expects. We don't need to complicate our scheme, because the application can handle any validation that it wants to do on the message, including size. Just as existing signature schemes provide no mechanism for limiting message size, neither should we.
