### ISSUE TITLE
What is SHA256("https://w3.org/2016/02/xxx-xxx.html#rsa-sha-256")?

### ISSUE THREAD

**Issue by jtremback** [interledger/five-bells-condition#6]
In RSA-SHA256, and in Threshold-SHA256, you have  `SHA256("https://w3.org/2016/02/xxx-xxx.html#rsa-sha-256")` you explained this to me at one point, but I forgot why it's there. And why isn't it on SHA256?

**Comment by justmoon** [comment]
There is a general rule of thumb when generating cryptographic protocols to ensure that hashes are unambiguous. Meaning a hash in one part of your (or anyone else's) protocol should never match any hash in any other part of your (or anyone else's) protocol, even if the data afterwards somehow happens to be the same.

The best way to ensure that is to start the content of your hash with a domain-specific, globally unique prefix. I figured URLs are a good way to get a value that's likely to be globally unique, but they're quite long and they have different lengths, so a hash of a URL is a bit nicer and still ensures the uniqueness.

So much for the general principle, we can do more thinking on whether it's a good idea in this particular case.

**Comment by jtremback** [comment]
Oh, so the URL is a URL that you intend for the w3 to make for Interledger? and the xxx is a placeholder? Seems to be guarding against some very slim odds of collision. 

If this is a good practice, why not apply it to all serialized data?

**Comment by justmoon** [comment]
> If this is a good practice, why not apply it to all serialized data?

The practice is to make sure hashes are unique and it's worth doing usually because it doesn't cost you any additional bytes. (Hash doesn't get any longer just because you put more into it.) Sometimes it makes sense to add unique identifiers in the serialization format, but there you are paying for it with a lot of redundant data you have to transfer every time, so you should have a bit stronger reason to do it.

**Comment by jtremback** [comment]
So the attack this is guarding against is someone tricking you into signing something from a completely different protocol that happens to be a valid crypto condition?

**Comment by justmoon** [comment]
Doesn't have to be from a different protocol. Could be somebody made a proprietary extension to the protocol or maybe we define two cryptoconditions that somehow result in the same bitmask.

Let's try to make a collision:

Think of a threshold condition. It starts with a threshold varuint, then the varray length and then a condition, so you probably have only three or so bytes that you have to force.

Ok, now let's say we also construct a RSA condition. That one starts with a modulus. The first part is the length of the modulus, which you don't have that much flexibility for. But that's the threshold varuint in the other condition, which you can pretty much freely pick. So you pick a 2048-bit modulus (size 256) so we just set the threshold to 256.

Then on the threshold condition side we need to have a reasonable number subconditions, so let's say we want that to be 10. So now we just generate moduli until we find one that starts with 0x0a. Then we need... and so on.

You could quite possibly find a valid threshold condition that has the exact same content byte-for-byte as an RSA condition. Certainly it's very, very likely that as we add more conditions there will one day be a condition that exactly matches some other condition of a different type.

The problem with that is that now I can potentially get you to generate a certain condition, let's say by telling you my public key 0x10999-you-just-got-owned. You'll put it into a 2-of-2 condition thinking is safe, but in actuality I have caused you to create something which may be safe as a 2-of-2, but which I can trivially fulfill when interpreted as a SHA256 hashlock condition let's say.

The fact that I can't think of a way to make this attack practical doesn't give me **any** comfort. I don't want to have to go through every combination of condition types every single time we add a new condition. We need to make sure that there is never any ambiguity by prefixing with a unique value.

Now it's probably totally fine to take out the SHA256(url) stuff since the hash still starts with the BITMASK. But if we do that should make a rule saying that this is not the full bitmask (all condition types that appear), but rather just the bit representing the top level condition. (Otherwise you have the possibility of ambiguity again.)

Adrian also suggested that an IANA-run registry of condition types is the more typical solution for RFCs, so that's what we should probably go with.

**Comment by jtremback** [comment]
I'm sold.

**Comment by jtremback** [comment]
> You'll put it into a 2-of-2 condition thinking is safe, but in actuality I have caused you to create something which may be safe as a 2-of-2, but which I can trivially fulfill when interpreted as a SHA256 hashlock condition let's say

What is the situation in which someone neglects to read the bitmask, or the bitmask does not accurately represent the thing that is being parsed? Isn't this the thing that needs to be fixed?

**Comment by jtremback** [comment]
For instance, what if someone puts some other condition's payload as the preimage for a hashlock? If we can't rely on the bitmask, wouldn't this be the same kind of attack, but simpler?

**Comment by justmoon** [comment]
> What is the situation in which someone neglects to read the bitmask, or the bitmask does not accurately represent the thing that is being parsed? Isn't this the issue that needs to be fixed?

Not quite, but you've made me realize that the issue is narrower than I thought. It's only relevant for conditions that can have subconditions. Let's call them structural conditions. Right now the only one we have is THRESHOLD-SHA-256. Suppose we added another structural condition that was 256-bits long, e.g. THRESHOLD-SHA-3-256. Now if there was any way to create a fulfillment payload that was valid both as a THRESHOLD-SHA-256 condition and a THRESHOLD-SHA-3-256, we would have ambiguity and with it a possible exploit.

The fix is still to prevent the ambiguity. We have three options:

1. We can make the conditions unambiguous by adding a dedicated type field (as suggested in #5) or
2. We can add a `TYPE_BIT` field in the hash for all structural conditions or
3. We can just cross our fingers and hope that no future standards authors or implementers end up adding a structural condition where a collision is possible.

My vote would be option no 2. We're not adding any data to the protocol, since the hash is fixed-length anyway. And we are preventing any possibility of ambiguity, even when future authors of crypto-condition types are careless.
